name: monsoon-pod
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - adlfs
  - basemap
  - bottleneck
  - cartopy
  - dask
  - gcsfs
  - ipykernel
  - matplotlib
  - netcdf4
  - numpy
  - planetary-computer
  - proplot
  - pystac-client
  - scipy
  - xarray
  - xesmf
  - zarr